trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      try {
        Write-Output "Starting the restart process..."
        Write-Information "Attempting to import module..."
        Import-Module "C:\Program Files\Microsoft Dynamics 365 Business Central\160\Service\NavAdminTool.ps1" -ErrorAction Stop
        Write-Output "Module imported successfully."
        Write-Information "Issuing restart command..."
        Restart-NAVServerInstance Kencotemp
        Write-Output "Restart command issued for Kencotemp."
      } catch {
        Write-Error "An error occurred: $_"
        throw
      }
  displayName: 'Restart NAV Server Instance'
