trigger:
- main

pool:
  name: $(vm)



steps:
- script: |
    echo "Running on VM: $(vm)"
  displayName: 'Display VM Name'

- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |
        Write-Output "Starting the restart process..."
        Import-Module "C:\Program Files\Microsoft Dynamics 365 Business Central\160\Service\NavAdminTool.ps1"
        Write-Output "Module imported successfully."
        Restart-NAVServerInstance $(service)
        Write-Output "Restart command issued for $(service)."
  displayName: 'Restart NAV Server Instance'
