trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Run Chrome to open YouTube
- powershell: Start-Process "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" "https://www.youtube.com"
  displayName: 'Run YouTube in Chrome'
