trigger:
- main

pool:
  vmImage: ubuntu-latest  # Change this to 'windows-latest' if you're using a Windows VM

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Diagnostic step to print environment variables
- script: printenv
  displayName: 'Print environment variables'

# Diagnostic step to print agent details
- script: |
    echo "Agent Name: $AGENT_NAME"
    echo "Agent Machine Name: $AGENT_MACHINENAME"
    echo "Agent OS: $AGENT_OS"
    echo "Agent OS Architecture: $AGENT_OSARCHITECTURE"
  displayName: 'Print agent details'

# Install Chrome on Ubuntu
- script: |
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo apt-get update
    sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
  displayName: 'Install Google Chrome'

# Run Chrome to open YouTube on Ubuntu
- script: |
    google-chrome --no-sandbox --disable-gpu https://www.youtube.com &
  displayName: 'Run YouTube in Chrome'
