trigger:
- main

pool:
  name: Pipeline

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
  # Create a folder in a specific directory (PowerShell)
- powershell: |
    $folderPath = "C:\test1"
    if (!(Test-Path -Path $folderPath)) {
        New-Item -ItemType Directory -Path $folderPath
    }
  displayName: 'Create a folder in the directory'
